//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7B_ESNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Availability
    {
        public int FacilityID { get; set; }
        public System.DateTime DateOfBooking { get; set; }
        public bool Slot1 { get; set; }
        public bool Slot2 { get; set; }
        public bool Slot3 { get; set; }
        public bool Slot4 { get; set; }
        public bool Slot5 { get; set; }
        public bool Slot6 { get; set; }
        public bool Slot7 { get; set; }
        public bool Slot8 { get; set; }
        public bool Slot9 { get; set; }
        public bool Slot10 { get; set; }
        public bool Slot11 { get; set; }
        public bool Slot12 { get; set; }
    
        public virtual Facility Facility { get; set; }
    }
}
