//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7B_ESNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public int FacilityID { get; set; }
        public int MemberID { get; set; }
        public System.DateTime DateOfBooking { get; set; }
        public int Slot { get; set; }
        public string Status { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual Member Member { get; set; }
        public virtual Slot Slot1 { get; set; }
    }
}
