//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7B_ESNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingView
    {
        public int BookingID { get; set; }
        public System.DateTime DateOfBooking { get; set; }
        public string FacilityName { get; set; }
        public string Location { get; set; }
        public decimal Cost { get; set; }
        public string SlotTime { get; set; }
        public int MemberID { get; set; }
        public string MemberName { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
    }
}
