//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7B_ESNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Occupancy
    {
        public int FacilityID { get; set; }
        public string FacilityName { get; set; }
        public int DayNum { get; set; }
        public string Day_Of_Week { get; set; }
        public double Occupancy1 { get; set; }
        public System.DateTime DateOfBooking { get; set; }
    }
}
