//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7B_ESNET
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SA46Team07BEntities : DbContext
    {
        public SA46Team07BEntities()
            : base("name=SA46Team07BEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Availability> Availabilities { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Facility> Facilities { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Slot> Slots { get; set; }
        public virtual DbSet<BookingView> BookingViews { get; set; }
        public virtual DbSet<Occupancy> Occupancies { get; set; }
    }
}
